server:
  port: 8080
spring:
  application:
    name: catalogos
  datasource:
    url: jdbc:postgresql://localhost:5432/gasolinera
    username: postgres
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        show-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true